sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
env:
- DJANGO="django>=1.6.0,<1.7.0"
- DJANGO="django>=1.7.0,<1.8.0"
- DJANGO="django>=1.8.0,<1.9.0"
- DJANGO="django>=1.9.0,<1.10.0"
matrix:
  exclude:
  - python: '2.6'
    env: DJANGO="django>=1.7.0,<1.8.0"
  - python: '2.6'
    env: DJANGO="django>=1.8.0,<1.9.0"
  - python: '2.6'
    env: DJANGO="django>=1.9.0,<1.10.0"
  - python: '3.3'
    env: DJANGO="django>=1.4.0,<1.5.0"
  - python: '3.3'
    env: DJANGO="django>=1.9.0,<1.10.0"
before_install:
- pip install codecov
install:
- travis_retry pip install $DJANGO -e .
script:
- coverage run --source=capture_tag runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: WWNa4MHf50AOybB+XW9UKXCk/9Q8r++Jc4xTdEib43rj4odH9wxIaTRrzAbbpo3EO2gYuLgq6mMbaIZPD5l2UmgSnyuIbeYAAKIQblT+8XMamtXwnSS5j9vfBXYdj54rTlh+jKwEMW/JiQKl+SQpfQ2v1NMvYO63m89Ev9vXvcU=
    on_success: never
    on_failure: always
